/*
 *
 *  Purpose          :	 To show and hide the account details generated by "generateData" JS file.
 *
 *  Created Date     :  	24/1/2025
 *
 *  Created By       :  	Shubham Raut
 *
 *  Revision Logs    :  	V_1.0 - Created - Shubham Raut
 *
 */
import { LightningElement, track } from 'lwc';
import generateData from './generateData';

const columns =
    [
        { label: 'Name', fieldName: 'Name' },
        { label: 'Phone', fieldName: 'Phone', type: 'phone' },
        { label: 'Website', fieldName: 'Website', type: 'url' },
        { label: 'Amount', fieldName: 'Amount', type: 'currency' }
    ];

export default class AccountManager extends LightningElement {

    @track dataAcc = null;
    @track columnsToShow = columns;
    error = null;

    // Called on click of Show Accounts
    showAccHandler() {

        try {
            // will Generate Demo data using generateData JS file
            let data = generateData({ amountOfRecords: 10 });

            if (data.length > 0) {
                this.dataAcc = data;
            } else {
                throw new Error('Error in Generating data');
            }
        } catch (e) {
            this.error = e.message;
        }
    }

    // Called on click of Hide Accounts
    hideAccHandler() {
        this.dataAcc = null;
    }
}